version: '3'

services:
  php:
    build: ./docker/php
    image: php:7.2-apache-cakephp3
    container_name: baby-record-backend_php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./:/var/www/html
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      - baby-record
  mysql:
    image: mysql:5.6
    container_name: baby-record-backend_mysql
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - baby-record
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: baby-record-backend_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./docker/data/phpmyadmin/sessions:/sessions
    networks:
      - baby-record
networks:
    baby-record:
      driver: bridge
